Datamesh handle the requests for all methods
buildly-release-management/buildly-core pull request #38
Opened 2022-01-19 14:31 UTC by mthombare

## Purpose
- Datamesh handle the requests for all methods

## Approach
- Written functions to perform all requests via datamesh

### Further Info
Ticket number: 
#31 #35 #27 #33 #34 

@yasmin2496

2022-01-20 07:17 UTC, yasmin2496 commented on gateway/request.py
> +    def retrieve_relationship_data(self, datamesh_relationship: any, query_params: str, request_param: any, resp_data: Union[dict, list]):
Can these functions be placed alongwith other utility functions of datamesh @mthombare

2022-01-20 07:17 UTC, yasmin2496 requested changes
Looks good other than the utilities need to be inside datamesh folder

2022-01-20 07:42 UTC, mthombare commented on gateway/request.py
> +    def retrieve_relationship_data(self, datamesh_relationship: any, query_params: str, request_param: any, resp_data: Union[dict, list]):
yes, I'm going to do that once I finish the current test case #33

2022-01-25 12:38 UTC, yasmin2496 approved these changes

2022-01-25 12:41 UTC, merged